# Generated by Django 6.0.4 on 2026-04-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
